package com.example.currencyexchange.model

data class CurrencyInfo(
    val code: String,        // np. "PLN"
    val name: String,        // np. "Polish Złoty"
    val countryCode: String  // np. "pl" (dla flagcdn)
)

object CurrencyProvider {
    val currencies = mapOf(
        "AED" to CurrencyInfo("AED", "UAE Dirham", "ae"), // klucz wartość
        "AFN" to CurrencyInfo("AFN", "Afghan Afghani", "af"),
        "ALL" to CurrencyInfo("ALL", "Albanian Lek", "al"),
        "AMD" to CurrencyInfo("AMD", "Armenian Dram", "am"),
        "ANG" to CurrencyInfo("ANG", "Netherlands Antillian Guilder", "an"),
        "AOA" to CurrencyInfo("AOA", "Angolan Kwanza", "ao"),
        "ARS" to CurrencyInfo("ARS", "Argentine Peso", "ar"),
        "AUD" to CurrencyInfo("AUD", "Australian Dollar", "au"),
        "AWG" to CurrencyInfo("AWG", "Aruban Florin", "aw"),
        "AZN" to CurrencyInfo("AZN", "Azerbaijani Manat", "az"),
        "BAM" to CurrencyInfo("BAM", "Bosnia and Herzegovina Mark", "ba"),
        "BBD" to CurrencyInfo("BBD", "Barbados Dollar", "bb"),
        "BDT" to CurrencyInfo("BDT", "Bangladeshi Taka", "bd"),
        "BGN" to CurrencyInfo("BGN", "Bulgarian Lev", "bg"),
        "BHD" to CurrencyInfo("BHD", "Bahraini Dinar", "bh"),
        "BIF" to CurrencyInfo("BIF", "Burundian Franc", "bi"),
        "BMD" to CurrencyInfo("BMD", "Bermudian Dollar", "bm"),
        "BND" to CurrencyInfo("BND", "Brunei Dollar", "bn"),
        "BOB" to CurrencyInfo("BOB", "Bolivian Boliviano", "bo"),
        "BRL" to CurrencyInfo("BRL", "Brazilian Real", "br"),
        "BSD" to CurrencyInfo("BSD", "Bahamian Dollar", "bs"),
        "BTN" to CurrencyInfo("BTN", "Bhutanese Ngultrum", "bt"),
        "BWP" to CurrencyInfo("BWP", "Botswana Pula", "bw"),
        "BYN" to CurrencyInfo("BYN", "Belarusian Ruble", "by"),
        "BZD" to CurrencyInfo("BZD", "Belize Dollar", "bz"),
        "CAD" to CurrencyInfo("CAD", "Canadian Dollar", "ca"),
        "CDF" to CurrencyInfo("CDF", "Congolese Franc", "cd"),
        "CHF" to CurrencyInfo("CHF", "Swiss Franc", "ch"),
        "CLP" to CurrencyInfo("CLP", "Chilean Peso", "cl"),
        "CNY" to CurrencyInfo("CNY", "Chinese Renminbi", "cn"),
        "COP" to CurrencyInfo("COP", "Colombian Peso", "co"),
        "CRC" to CurrencyInfo("CRC", "Costa Rican Colon", "cr"),
        "CUP" to CurrencyInfo("CUP", "Cuban Peso", "cu"),
        "CVE" to CurrencyInfo("CVE", "Cape Verdean Escudo", "cv"),
        "CZK" to CurrencyInfo("CZK", "Czech Koruna", "cz"),
        "DJF" to CurrencyInfo("DJF", "Djiboutian Franc", "dj"),
        "DKK" to CurrencyInfo("DKK", "Danish Krone", "dk"),
        "DOP" to CurrencyInfo("DOP", "Dominican Peso", "do"),
        "DZD" to CurrencyInfo("DZD", "Algerian Dinar", "dz"),
        "EGP" to CurrencyInfo("EGP", "Egyptian Pound", "eg"),
        "ERN" to CurrencyInfo("ERN", "Eritrean Nakfa", "er"),
        "ETB" to CurrencyInfo("ETB", "Ethiopian Birr", "et"),
        "EUR" to CurrencyInfo("EUR", "Euro", "eu"),
        "FJD" to CurrencyInfo("FJD", "Fiji Dollar", "fj"),
        "FKP" to CurrencyInfo("FKP", "Falkland Islands Pound", "fk"),
        "GBP" to CurrencyInfo("GBP", "Pound Sterling", "gb"),
        "GEL" to CurrencyInfo("GEL", "Georgian Lari", "ge"),
        "GHS" to CurrencyInfo("GHS", "Ghanaian Cedi", "gh"),
        "GIP" to CurrencyInfo("GIP", "Gibraltar Pound", "gi"),
        "GMD" to CurrencyInfo("GMD", "Gambian Dalasi", "gm"),
        "GNF" to CurrencyInfo("GNF", "Guinean Franc", "gn"),
        "GTQ" to CurrencyInfo("GTQ", "Guatemalan Quetzal", "gt"),
        "GYD" to CurrencyInfo("GYD", "Guyanese Dollar", "gy"),
        "HKD" to CurrencyInfo("HKD", "Hong Kong Dollar", "hk"),
        "HNL" to CurrencyInfo("HNL", "Honduran Lempira", "hn"),
        "HRK" to CurrencyInfo("HRK", "Croatian Kuna", "hr"),
        "HTG" to CurrencyInfo("HTG", "Haitian Gourde", "ht"),
        "HUF" to CurrencyInfo("HUF", "Hungarian Forint", "hu"),
        "IDR" to CurrencyInfo("IDR", "Indonesian Rupiah", "id"),
        "ILS" to CurrencyInfo("ILS", "Israeli New Shekel", "il"),
        "INR" to CurrencyInfo("INR", "Indian Rupee", "in"),
        "IQD" to CurrencyInfo("IQD", "Iraqi Dinar", "iq"),
        "ISK" to CurrencyInfo("ISK", "Icelandic Króna", "is"),
        "JMD" to CurrencyInfo("JMD", "Jamaican Dollar", "jm"),
        "JOD" to CurrencyInfo("JOD", "Jordanian Dinar", "jo"),
        "JPY" to CurrencyInfo("JPY", "Japanese Yen", "jp"),
        "KES" to CurrencyInfo("KES", "Kenyan Shilling", "ke"),
        "KGS" to CurrencyInfo("KGS", "Kyrgyzstani Som", "kg"),
        "KHR" to CurrencyInfo("KHR", "Cambodian Riel", "kh"),
        "KMF" to CurrencyInfo("KMF", "Comorian Franc", "km"),
        "KRW" to CurrencyInfo("KRW", "South Korean Won", "kr"),
        "KWD" to CurrencyInfo("KWD", "Kuwaiti Dinar", "kw"),
        "KYD" to CurrencyInfo("KYD", "Cayman Islands Dollar", "ky"),
        "KZT" to CurrencyInfo("KZT", "Kazakhstani Tenge", "kz"),
        "LAK" to CurrencyInfo("LAK", "Lao Kip", "la"),
        "LBP" to CurrencyInfo("LBP", "Lebanese Pound", "lb"),
        "LKR" to CurrencyInfo("LKR", "Sri Lanka Rupee", "lk"),
        "LRD" to CurrencyInfo("LRD", "Liberian Dollar", "lr"),
        "LSL" to CurrencyInfo("LSL", "Lesotho Loti", "ls"),
        "LYD" to CurrencyInfo("LYD", "Libyan Dinar", "ly"),
        "MAD" to CurrencyInfo("MAD", "Moroccan Dirham", "ma"),
        "MDL" to CurrencyInfo("MDL", "Moldovan Leu", "md"),
        "MGA" to CurrencyInfo("MGA", "Malagasy Ariary", "mg"),
        "MKD" to CurrencyInfo("MKD", "Macedonian Denar", "mk"),
        "MMK" to CurrencyInfo("MMK", "Burmese Kyat", "mm"),
        "MNT" to CurrencyInfo("MNT", "Mongolian Tögrög", "mn"),
        "MOP" to CurrencyInfo("MOP", "Macanese Pataca", "mo"),
        "MRU" to CurrencyInfo("MRU", "Mauritanian Ouguiya", "mr"),
        "MUR" to CurrencyInfo("MUR", "Mauritian Rupee", "mu"),
        "MVR" to CurrencyInfo("MVR", "Maldivian Rufiyaa", "mv"),
        "MWK" to CurrencyInfo("MWK", "Malawian Kwacha", "mw"),
        "MXN" to CurrencyInfo("MXN", "Mexican Peso", "mx"),
        "MYR" to CurrencyInfo("MYR", "Malaysian Ringgit", "my"),
        "MZN" to CurrencyInfo("MZN", "Mozambican Metical", "mz"),
        "NAD" to CurrencyInfo("NAD", "Namibian Dollar", "na"),
        "NGN" to CurrencyInfo("NGN", "Nigerian Naira", "ng"),
        "NIO" to CurrencyInfo("NIO", "Nicaraguan Córdoba", "ni"),
        "NOK" to CurrencyInfo("NOK", "Norwegian Krone", "no"),
        "NPR" to CurrencyInfo("NPR", "Nepalese Rupee", "np"),
        "NZD" to CurrencyInfo("NZD", "New Zealand Dollar", "nz"),
        "OMR" to CurrencyInfo("OMR", "Omani Rial", "om"),
        "PAB" to CurrencyInfo("PAB", "Panamanian Balboa", "pa"),
        "PEN" to CurrencyInfo("PEN", "Peruvian Sol", "pe"),
        "PGK" to CurrencyInfo("PGK", "Papua New Guinea Kina", "pg"),
        "PHP" to CurrencyInfo("PHP", "Philippine Peso", "ph"),
        "PKR" to CurrencyInfo("PKR", "Pakistani Rupee", "pk"),
        "PLN" to CurrencyInfo("PLN", "Polish Złoty", "pl"),
        "PYG" to CurrencyInfo("PYG", "Paraguayan Guaraní", "py"),
        "QAR" to CurrencyInfo("QAR", "Qatari Riyal", "qa"),
        "RON" to CurrencyInfo("RON", "Romanian Leu", "ro"),
        "RSD" to CurrencyInfo("RSD", "Serbian Dinar", "rs"),
        "RUB" to CurrencyInfo("RUB", "Russian Ruble", "ru"),
        "RWF" to CurrencyInfo("RWF", "Rwandan Franc", "rw"),
        "SAR" to CurrencyInfo("SAR", "Saudi Riyal", "sa"),
        "SBD" to CurrencyInfo("SBD", "Solomon Islands Dollar", "sb"),
        "SCR" to CurrencyInfo("SCR", "Seychellois Rupee", "sc"),
        "SDG" to CurrencyInfo("SDG", "Sudanese Pound", "sd"),
        "SEK" to CurrencyInfo("SEK", "Swedish Krona", "se"),
        "SGD" to CurrencyInfo("SGD", "Singapore Dollar", "sg"),
        "SHP" to CurrencyInfo("SHP", "Saint Helena Pound", "sh"),
        "SLE" to CurrencyInfo("SLE", "Sierra Leonean Leone", "sl"),
        "SOS" to CurrencyInfo("SOS", "Somali Shilling", "so"),
        "SRD" to CurrencyInfo("SRD", "Surinamese Dollar", "sr"),
        "SSP" to CurrencyInfo("SSP", "South Sudanese Pound", "ss"),
        "STN" to CurrencyInfo("STN", "São Tomé and Príncipe Dobra", "st"),
        "SYP" to CurrencyInfo("SYP", "Syrian Pound", "sy"),
        "SZL" to CurrencyInfo("SZL", "Eswatini Lilangeni", "sz"),
        "THB" to CurrencyInfo("THB", "Thai Baht", "th"),
        "TJS" to CurrencyInfo("TJS", "Tajikistani Somoni", "tj"),
        "TMT" to CurrencyInfo("TMT", "Turkmenistan Manat", "tm"),
        "TND" to CurrencyInfo("TND", "Tunisian Dinar", "tn"),
        "TOP" to CurrencyInfo("TOP", "Tongan Paʻanga", "to"),
        "TRY" to CurrencyInfo("TRY", "Turkish Lira", "tr"),
        "TTD" to CurrencyInfo("TTD", "Trinidad and Tobago Dollar", "tt"),
        "TWD" to CurrencyInfo("TWD", "New Taiwan Dollar", "tw"),
        "TZS" to CurrencyInfo("TZS", "Tanzanian Shilling", "tz"),
        "UAH" to CurrencyInfo("UAH", "Ukrainian Hryvnia", "ua"),
        "UGX" to CurrencyInfo("UGX", "Ugandan Shilling", "ug"),
        "USD" to CurrencyInfo("USD", "United States Dollar", "us"),
        "UYU" to CurrencyInfo("UYU", "Uruguayan Peso", "uy"),
        "UZS" to CurrencyInfo("UZS", "Uzbekistani So'm", "uz"),
        "VES" to CurrencyInfo("VES", "Venezuelan Bolívar", "ve"),
        "VND" to CurrencyInfo("VND", "Vietnamese Đồng", "vn"),
        "VUV" to CurrencyInfo("VUV", "Vanuatu Vatu", "vu"),
        "WST" to CurrencyInfo("WST", "Samoan Tālā", "ws"),
        "XAF" to CurrencyInfo("XAF", "Central African CFA Franc", "cf"),
        "XCD" to CurrencyInfo("XCD", "East Caribbean Dollar", "ag"),
        "XOF" to CurrencyInfo("XOF", "West African CFA franc", "sn"),
        "XPF" to CurrencyInfo("XPF", "CFP Franc", "pf"),
        "YER" to CurrencyInfo("YER", "Yemeni Rial", "ye"),
        "ZAR" to CurrencyInfo("ZAR", "South African Rand", "za"),
        "ZMW" to CurrencyInfo("ZMW", "Zambian Kwacha", "zm"),
        "ZWL" to CurrencyInfo("ZWL", "Zimbabwean Dollar", "zw")
    )

    fun getFlagUrl(currencyCode: String, width: Int = 640): String? {
        val countryCode = currencies[currencyCode]?.countryCode ?: return null
        return "https://flagcdn.com/w$width/$countryCode.png"
    }
}